APP_NAME = "infinityu"
APP_VERSION = "0.1.0-alpha"
APP_AUTHOR = "João Gabriel"
APP_GITHUB = "https://github.com/Patolinux123"
APP_TECH = "Made with PySide6 & Qt"
APP_TAGLINE = "Acho que funciona (não funciona ainda)"
